server:
  name: 'Im-Services'
  listen: ':8000'
  mode: 'debug' # gin的运行模式 debug, release, test
  env: 'local' #local production testing
  lang: 'zh'
  coroutinePool: 100000 # 启动的协程池数量
  node: '127.0.0.1:9505' #当前服务集群节点
  serviceOpen: false # 开启集群服务
  grpcListen: ':8002' # grpc端口
  filePath: '/storage/pic'
mysql:
  host: '127.0.0.1'
  port: 3306
  database: 'im'
  username: 'admin'
  password: 'Gxy221999'
  charset: 'utf8mb4'
log:
  level: 'debug' # 开发时推荐使用 "debug" 或者 "info" ，生产环境下使用 "error"
  type: 'daily' #"single" 独立的文件  "daily" 按照日期每日一个
  filename: 'storage/logs/logs.log'
  maxSize: 64 # 保存最大单位 M
  maxBackup: 30 #最多保存日志文件数，0 为不限，MaxAge 到了还是会删
  maxAge: 7 #最多保存多少天
  compress: false #是否压缩
jwt:
  secret: 'acb2ca5bc8d7fb2ef8f890f1be15d964' #密钥
  ttl: 640000 #
redis:
  host: '127.0.0.1'
  port: 6379
  password:
  db: 1
  pool: 15 #连接池 默认为4倍cpu数
  conn: 10 #最小空闲连接数
mail:
  driver: 'smtp'
  host: 'smtp.qq.com'
  name: '893376179@qq.com'
  password: 'dodrgqhydlykbeda'
  port: 465
  encryption: 'ssl'
  fromName: 'Im-Services'
kafka:
  host: '127.0.0.1'
  port: 9506
nsq:
  lookupHost: '127.0.0.1:4161'
  nsqHost: '127.0.0.1:4150'
qiniu:
  accessKey: '8LaCUdU4LgsP2ju_9ESnqSa80WC4eqCaBG62q9WZ'
  secretKey: 'gJA6gC_4LUwB1L6jIr30RVjqhpu_B_Hd3b7AkWws'
  bucket: 'server-group'
  domain: 'https://.top'
github:
  appId: ''
  appKey: ''
  redirectUrl: ''
gobot:
  email: 'intelligence@chat.com'
  password: 'intelligence@30434---343'
  name: '机器人'
  avatar: 'https://api.multiavatar.com/Binx%130.png#pic_center'
